### ISSUE TITLE
Rewrite User Section in Chat Basics Guide

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/guides#101]
Guide: [Skygear Chat Basics](https://docs.skygear.io/guides/chat/basics/js/)
Platform: All

Problems or Suggestions as follows:

A frequently asked question for chat user is: how do I get the user object?

The answer is inside [User Profile Best Practices](https://docs.skygear.io/guides/auth/user-profile/js/#retrieving-another-user-record-by-email-or-username)

I suggest we should add the following under the [Users](https://docs.skygear.io/guides/chat/basics/js/#users) section in the Chat Basics guide.

Replace the section with:

```
Real-time chat apps require a user login system and you can do it with [Skygear User Auth](https://docs.skygear.io/guides/auth/basics/js/). It offers various sign up methods - sign up with email, sign up with username and sign up with Facebook and Google account; It also integrate nicely if you have an backend (such as Rails / Node.js) to handle authentication.

Depends on your applications, you may want to do the following:
* [Keep a list of user's followers or contact list like most social apps](https://docs.skygear.io/guides/social-network/basics/js/)
* [Query for another user record by email or username](https://docs.skygear.io/guides/auth/user-profile/js/#retrieving-another-user-record-by-email-or-username)
* [Integrate Skygear User Auth with existing backend](Coming soon after https://github.com/SkygearIO/features/issues/56 is done)
```

**Comment by howawong** [comment]
@david90  shall we discuss because i am also working on the guide?

**Comment by chpapa** [comment]
@howawong I would prefer if you can finish your chat guide general update for the recent big changes and put it live first, coz I am answering supporting questions for the outdated guides recently.

After that we can made fine tune and minor changes like these iteratively.
