### ISSUE TITLE
Move auto deployment from skygear-doc to guides repository

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/guides#112]
- Move table of content `content.index.js` from skygear-doc to guides, as we found that after adding new pages in guides we always need to update the table of content. It makes sense to put the table of content here, so it should be updated along with the content
- We want merge guides will update the doc site, so decided to move the ci to this repository.

**Comment by chpapa** [comment]
moving CI meant spell check will apply to pull request? I think that is the biggest benefits lol.

but depends on how difficult I think it is not urgent.

**Comment by carmenlau** [comment]
Currently guides repo already have spell check for PR. Moving CI means that deployment part. We are going to move 2 things in this issue. The guides table of content and the auto deployment.

The benefits of change
1. Avoid forgetting update the table of content when we update the guides.
2. Merging guides PR will auto deploy the doc

Yes it is not urgent, but good to have!

**Comment by chpapa** [comment]
I think it have been completed?
