### ISSUE TITLE
Add sample code and explain for `createConversation`, how to get the conversation object returned in the error of DistinctByParticipants

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/guides#142]
Guide: Skygear Chat Basic
Platform: iOS/Android/JS

Problems or Suggestions as follows:

From https://github.com/SkygearIO/chat/pull/153, we have embed the existing conversation ID in the info section of error message, we should explain and show a sample code of how to use that to get the conversation object in the Chat Guide.

**Comment by chpapa** [comment]
@carmenlau I just want to be sure so I re-open this issue again. The issue should be about the guide for both iOS / Android / JS Guides, but if I'm not mistaken, It seems only android guide was fixed for this?

**Comment by carmenlau** [comment]
Sorry for miss that, right. JS and iOS part also need updates and we only updated the android part. Thanks for reminding.

**Comment by carmenlau** [comment]
@howawong I merged and deployed your update. Btw, do you think it would be better if we also update the sample code of `createDirectConversation`? Since `createDirectConversation` is also DistinctByParticipants
