### ISSUE TITLE
Wrong call in JS Cloud Function Guide

### ISSUE THREAD

**Issue by howawong** [SkygearIO/guides#156]
Guide: [cloud-function/http-endpoint/js.md]
Platform: [JS]

Problems or Suggestions as follows:

In https://github.com/SkygearIO/guides/blame/3530d01804172e0a31105af854c733e151b5879f/cloud-function/http-endpoint/js.md#L108
 the guide suggests `skygear.auth.currentUser()` can retrieve the current user, which is obviously wrong. Please correct it to be context parameter.

**Comment by chpapa** [comment]
@howawong if it is a one liner fix can you submit a PR or put the right one here quickly?

**Comment by howawong** [comment]
replace it with `options.context.user_id`

**Comment by carmenlau** [comment]
Updated in https://github.com/SkygearIO/guides/pull/154
