### ISSUE TITLE
No information on how to use the `pool parameter in database hook functions

### ISSUE THREAD

**Issue by cheungpat** [SkygearIO/guides#174]
Guide: Database Hooks
Platform: JS

Problems or Suggestions as follows:

The page https://docs.skygear.io/guides/cloud-function/database-hooks/js/ doesn’t actually mention how to use the `pool` parameter.

This problem is reported by @inDream.

**Comment by inDream** [comment]
@cheungpat There're examples in the next section, maybe only need to add a link or this issue can be closed with current doc.

Edit: It seems `options` parameter information is missing
