### ISSUE TITLE
[Deployment] Need to call update site-index to algolia after deployment

### ISSUE THREAD

**Issue by carmenlau** [SkygearIO/guides#176]
When we moved the deployment from skygear-doc to guides, we missed the `site-index` task that will update site-index to algolia after deployment

**Comment by ben181231** [comment]
@carmenlau the index in Algolia is rebuilt.

**Comment by cheungpat** [comment]
Try this https://www.algolia.com/doc/api-reference/api-methods/move-index/

**Comment by ben181231** [comment]
@cheungpat Got it. Implemented in [this commit](https://github.com/SkygearIO/skygear-doc/commit/4b00cd0).
