### ISSUE TITLE
k8s log section

### ISSUE THREAD

**Issue by elly0t** [SkygearIO/guides#272]
- [x] align with other docs, like placeholder
- [x] multiple contexts not included, add in a section for that
- [x] polish

**Comment by elly0t** [comment]
https://github.com/SkygearIO/guides/commit/0755d1d822ed3c977178cf22a06e2fcce01dedf7

**Comment by chpapa** [comment]
Thanks a lot! Do you think the current guide's description is good enough? The only one I found is under skycli > List of Commands.

There is one about `get-k8s-credentials`

I think is okay..
