### ISSUE TITLE
Explain CORS for Cloud Assets

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/guides#34]
Explain the problem, provide two solutions:

1) Use custom S3 buckets from Portals.
2) Host Web Frontend at skygeario.com

**Comment by tensiuyan** [comment]
Zach has a tip thats guide people setting up their custom S3 buckets

https://hackmd.io/MwEwjA7GBMCsBGBaAnAFgsRqDGwCGi88e0Www2eIwAbMABzzJA==

**Comment by chpapa** [comment]
@tensiuyan Please be noted there will be a user interface for this feature on portal soon oursky/skygear-portal#201
