### ISSUE TITLE
More detailed explanation on position arguments and keywords argument in lambda

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/guides#48]
Guide: cloud-function
Platform: py

Problems or Suggestions as follows:

JS x CloudCode can either support position argument by array or keywords args by object. The usage cannot mix up.

And if user pass in object to trigger lambda with position args, we will try our best to transform the object into correct array by matching the object key and argument names.

refs https://github.com/SkygearIO/guides/pull/46#issuecomment-291059776

**Comment by chpapa** [comment]
@rickmak does iOS and Android support both positional and named arguments for lambda too?

**Comment by rickmak** [comment]
I am sure iOS support both positional arguments and named arguments. refs: https://github.com/SkygearIO/skygear-SDK-iOS/blob/master/Pod/Classes/SKYLambdaOperation.m#L57

For android, seem only positional arguments is supported. refs: https://github.com/SkygearIO/skygear-SDK-Android/blob/master/skygear/src/main/java/io/skygear/skygear/LambdaRequest.java

**Comment by chpapa** [comment]
@rickmak I have created issue on Android skygeario/skygear-SDK-Android#120

For iOS, I think it supports internally but not as an interface? (Interface is always NSArray) I have created an issue: skygeario/skygear-SDK-iOS#89

If I was wrong, please help just close the issue above.

**Comment by rickmak** [comment]
http://cocoadocs.org/docsets/SKYKit/0.22.2/Classes/SKYLambdaOperation.html#//api/name/initWithAction:dictionaryArguments:
`- (instancetype)initWithAction:(NSString *)action dictionaryArguments:(NSDictionary *)arguments`

It supports `NSDictionary`.

**Comment by b123400** [comment]
Oh I wasn't aware of this API at all...

**Comment by chpapa** [comment]
@rickmak why callLambda doesn't have an nsdictionary version?

**Comment by rickmak** [comment]
After second thought, we may actually only promote one usage across all SDK/doc. i.e. keywords arguments .

It seem easier to write doc and explain.
