### ISSUE TITLE
Update H2 headers of Cloud Database / User Auth

### ISSUE THREAD

**Issue by tensiuyan** [SkygearIO/guides#55]
Guide: All guides under cloud databse and user authentication
Platform: All

Problems or Suggestions as follows:
As we have now implemented a TOC and it reads H2 header, we have to udpate the H2 header of the guides to make sure it is meaningful.

- [ ] cloud database
- [x] user authentication

**Comment by chpapa** [comment]
This issue is duplicated with #37. I'm revising this issue.

**Comment by chpapa** [comment]
Close for #37
