### ISSUE TITLE
Guides to add configuration to existing projects

### ISSUE THREAD

**Issue by mayyuen318** [SkygearIO/guides#57]
Reference: SkygearIO/features#52

Problems:
Developers who use Skygear are frustrated by adding the configurations to existing projects. 
This issue is to add guides for them to learn on how to add the configurations to different frameworks.

Guide: Guides to add configurations using different frameworks

- [ ] Angular 2 / Ionic 2 / React
- [ ] React Native

Platform: JS

**Comment by chpapa** [comment]
Duplicated with #58
