### ISSUE TITLE
Skygear JS SDK Integration Guide

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/guides#58]
Guide: Skygear JS SDK Integration Guide
Platform: JS

Integration guide for Skygear JS SDK for Angular2 / Ionic 2 / React.js.

Developers who use Skygear are frustrated by adding the configurations to existing projects. 
This issue is to add guides for them to learn on how to add the configurations to different frameworks.

Decide a guide for browsify / webpack depends on popularity.

**Comment by b123400** [comment]
Would like to finish https://github.com/SkygearIO/skygear-SDK-JS/issues/160#event-1037793839 before doing this issue, because both angular and ionic depends on webpack, which has issue with bundling optional external (react-native)
