### ISSUE TITLE
Update cloud code push notifications doc

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/guides#6]
_From @wallacesky on February 21, 2017 8:32_

The sample code doesn't mention the attribute of `topic` when using push notification token in Skygear

_Copied from original issue: SkygearIO/skygear-doc#475_

**Comment by tensiuyan** [comment]
Tidying up the issue.

In Python cloud functions doc ([APIs in cloud functions](https://docs.skygear.io/guides/cloud-function/calling-skygear-api/python/)):

1. Missing the attributes of 'topic' (JS has it)
2. Missing how to send notification to devices (JS has it)
