### ISSUE TITLE
Broken Link on Guides

### ISSUE THREAD

**Issue by seventhmoon** [SkygearIO/guides#60]
Guide: User Authentication Basics
Platform: JS

Problems or Suggestions as follows:
Section: User Login Status
Sub-Section: Getting the currently logged-in user
You can retrieve the current user from skygear.currentUser.

the link on skygear.currentUser to https://doc.esdoc.org/github.com/skygeario/skygear-SDK-JS/class/lib/container.js~Container.html#instance-get-currentUser is broken.

To get the latest information of the current user, you can call whoami():

the link on whoami() is also broken.

**Comment by chpapa** [comment]
Fixed at SkygearIO/skygear-SDK-JS#200
