### ISSUE TITLE
Regroup Skygear Cloud Database

### ISSUE THREAD

**Issue by Steven-Chan** [SkygearIO/guides#79]
Guide: Skygear Cloud Database
Platform: All

I think the current grouping of doc for skygear cloud database is a bit scattered for different usage.

For example, if I don't know what kind of record operation skygear cloud database can do, I would have no idea by looking at the toc.

For example, if I want to look for what skygear cloud database can do for reference kind operation, like how do I load save / query with reference or how many levels can I query with reference, I would have no idea by looking at the toc.

And for the `reference`, there is a part of `Relational Queries` in `Queries` and `Reference` in `Data Types`.

I expect I would know what Skygear Cloud Database can do just by looking at the toc.

My suggestion of pages / groups:
- Cloud Database Basics
  - Public Database and Private Database
  - database / record (what a database look like and what a record look like)
- Basic Record CRUD
  - create a record and basic data types
  - save
  - batch save
  - atomic
  - query with basic conditions, with links to more advanced conditions, e.g. relations
  - delete
- Work with reference
  - create a reference
  - save
  - transient include
  - query
- Work with assets
- Work with locations
- Advanced Data Types
  - Sequence
- Display a list using record query with overall count, sorting and pagination
  - query record count only
  - sorting
  - pagination
  - best practice for using reference with sorting and pagination
  - best practice for searching
- Cached Query
- Query Subscriptions
- Access Control 
  - Introduce ACL
  - read / write access
  - work with single user
- Access Control with User Role
  - define user role
  - assign / delete user record from user role
  - use of user role together with acl
- Record Type Access Control

**Comment by Steven-Chan** [comment]
I have updated the grouping, added `Display a list using record query with overall count, sorting and pagination`

**Comment by tensiuyan** [comment]
@Steven-Chan I will work on this issue. Just to confirm. The black bullet points are the section header right? (i.e. those that will be shown on the menu bar).

**Comment by tensiuyan** [comment]
Tracking progress

- [x] iOS
- [x] JS
- [ ] Android (need to wait for Kotlin sample codes)
