### ISSUE TITLE
User Profile Doc - add user discoverability and access control

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/guides#9]
_From @tensiuyan on February 16, 2017 4:38_

We should add the following items in the user profile guides 
- discoverability of a user
- access control

_Copied from original issue: SkygearIO/skygear-doc#456_

**Comment by chpapa** [comment]
Consider implement SkygearIO/skygear-server#54 when writing this guide? Many fellows want #54 and have to implement themselves, while this guide are supposed to explain common situations

**Comment by chpapa** [comment]
@rickmak @ben181231 @b123400 who would be assigned for this?

**Comment by chpapa** [comment]
TOC
* Discover users by email and username
* How to discover users by other attributes? (Cloud Function sample code)

How to handle attributes:
* Private, Non-listable (e.g. My SSH keys) => Private user record
* Public, Non-listable (e.g. Slug, unique path) => Private user record with Cloud Functions
* Public, Listable (e.g. Search all CUHK users) => Public user record

**Comment by chpapa** [comment]
This guide should also include the new signup User Profile interface at https://github.com/SkygearIO/skygear-server/issues/54

**Comment by tensiuyan** [comment]
We should write this guide after we have re-designed the user discoverability APIs.

ref skygeario/features#48
