### ISSUE TITLE
Move user related role API to Auth API Group (AuthContainer)

### ISSUE THREAD

**Issue by ben181231** [SkygearIO/guides#90]
Guide: Access Control (ACL)
Platform: iOS, Android, JS

After SkygearIO/skygear-SDK-iOS#114, SkygearIO/skygear-SDK-Android#145 and SkygearIO/skygear-SDK-JS#263, the user related role API has moved to Auth API Group. The guide need to be updated.

**Comment by chpapa** [comment]
I think this was completed? @rickmak
