### ISSUE TITLE
Upgrade Chat Guide to new Chat API

### ISSUE THREAD

**Issue by chpapa** [SkygearIO/guides#96]
Guide: Skygear Chat Quick Start / Skygear Chat Basic
Platform: iOS/Android/JS

Could @howawong help make some bullet points of what are the major area changed in the new API and need upgrade on the Guide?

After that, could @tensiuyan or @david90 help arrange someone to update the guides? As I was told the API reference have been completed.

**Comment by howawong** [comment]
- iOS

1.   Change `UserConversation` to `Conversation` 
2.  `fetchMessages` order parameter
3. deleting a message can  only be done via `deleteMessage` function, but not `record:delete`
4.  add *please help..*

- JS
1.   Change `UserConversation` to `Conversation` 
2.  `fetchMessages` order parameter
3. Remove *discoverUserByUsernames*

- Android
1.   Change `UserConversation` to `Conversation` 
2.  `fetchMessages` order parameter
3.  change `getPrivateDatabase ` to `getPublicDatabase ` in *Handling edit and delete messages*
4.  add *please help..*

And some inconsistencies among the different platforms.

**Comment by chpapa** [comment]
Thanks @howawong , I have unassigned you for now.

@tensiuyan do you think you can have someone to work on it? Or @david90 ?
